version: "3.8"

services:
  app:
    command: pnpm run preview --port 8081 --host app.synapse-ui.orb.local --mode production
    ports:
      - "8081:8081"
    build:
      context: ./
      # target: dev
      target: prod
    environment:
      - DEBUG="vite-tsconfig-paths"
    volumes:
      - ./:/app
      - /app/node_modules

  storybook:
    command: pnpm run storybook -- -p 6006 -h storybook.synapse-ui.orb.local
    build:
      context: ./
      target: dev

    environment:
      - DEBUG="vite-tsconfig-paths"
    ports:
      - "6006:6006"
    volumes:
      - ./:/app
      - /app/node_modules
