/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/rZKJqgsxpu0
 */
import { Button } from "@/components/ui/button"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { CardTitle, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"

export function IntakeFormPage() {
  return (
    <div className="bg-white p-8">
      <div className="flex justify-between border-b pb-2">
        <h1 className="text-xl font-semibold">Intake Form</h1>
        <span className="text-sm text-gray-500">Last Updated 7-8-2022</span>
      </div>
      <div className="flex mt-6">
        <div className="w-1/4 pr-4">
          <nav className="flex flex-col space-y-1">
            <Button className="text-left text-blue-600 bg-blue-100 rounded-none py-2 px-4">Areas Of Concern</Button>
            <Button className="text-left rounded-none py-2 px-4">Clinical Summary</Button>
            <Button className="text-left rounded-none py-2 px-4">Assessment Screenings</Button>
            <Button className="text-left rounded-none py-2 px-4">Biopsychosocialspiritual</Button>
            <Button className="text-left rounded-none py-2 px-4">Medication Information</Button>
            <Button className="text-left rounded-none py-2 px-4">CoCM Information</Button>
          </nav>
        </div>
        <div className="w-3/4 pl-4 border-l">
          <div className="mb-6">
            <h2 className="text-lg font-semibold mb-3">Areas Of Concern</h2>
            <div className="flex flex-col space-y-4">
              <Select>
                <SelectTrigger id="primary-concern">
                  <SelectValue placeholder="Select Area of Concern" />
                </SelectTrigger>
                <SelectContent position="popper">
                  <SelectItem value="concern1">Concern 1</SelectItem>
                  <SelectItem value="concern2">Concern 2</SelectItem>
                </SelectContent>
              </Select>
              <Select>
                <SelectTrigger id="secondary-concern">
                  <SelectValue placeholder="Select Area of Concern" />
                </SelectTrigger>
                <SelectContent position="popper">
                  <SelectItem value="concern1">Concern 1</SelectItem>
                  <SelectItem value="concern2">Concern 2</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>
          <div>
            <h2 className="text-lg font-semibold mb-3">Clinical Summary</h2>
            <p className="text-sm mb-6">
              Telehealth session completed with patient via (phone/video) who was at (fill in address & location) during
              the session. Confirmed identity via patient DOB. Patient consented to receive services via telehealth.
              Patient informed that they will be billed as normal for this session. Patient informed that there are
              inherent confidentiality risks with electronic communication and potential for technology failure. There
              is an emergency procedure in place should the need arise which was discussed with the patient. Emergency
              Contact: (name) (phone number).
            </p>
            <p className="text-sm">
              Informed consent was reviewed with patient and patient (provided verbal consent/ signed their consent) BHM
              offered to email/copy informed consent. Patient declined/ patient consented to email/copy.
            </p>
            <p className="text-sm my-6">
              Based upon assessment and initial review, the following therapeutic interventions should be considered:
              Cognitive Behavioral Therapy, Counseling/Talk Therapy, Motivational Interviewing
            </p>
            <p className="text-sm">
              Additional notes related to preliminary care plan: Patient and clinician discussed shared behavioral
              health and physical health goals for future Tx. Patient denied any other behavioral health Tx in the last
              12 months OR advised previous behavioral health treatment with "***". No recommendation for an external
              referral at this time OR Referral recommended for "***"
            </p>
          </div>
        </div>
        <div className="w-1/4 pl-4">
          <Card className="w-full">
            <CardHeader>
              <CardTitle>Jane Doe</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-sm">
                <p>Born 01-01-1980</p>
                <p>Female</p>
                <p>+1 480 254 0970</p>
                <p>janedoe@gmail.com</p>
              </div>
            </CardContent>
            <CardFooter className="flex justify-end">
              <Button variant="outline">Save Draft</Button>
              <Button className="ml-2">Save And Sign Intake</Button>
            </CardFooter>
          </Card>
        </div>
      </div>
    </div>
  )
}
